//██████ DOC https://supabase.com/docs/guides/database/tables?queryGroups=language&language=sql
import {useEffect, useState} from "react"
// eslint-disable-next-line no-restricted-imports
import {Alert, Button, Platform, StyleSheet, Text, View} from "react-native"
import {createClient} from "@supabase/supabase-js"
import {useDispatch} from "react-redux"
import {mediaPostCreateAPI} from "../../../state/enities/lib/crudPosts/api/mediaPostCreateAPI"
import {mediaPostDeleteAPI} from "../../../state/enities/lib/crudPosts/api/mediaPostDeleteAPI"
import {mediaPostReadAPI} from "../../../state/enities/lib/crudPosts/api/mediaPostReadAPI"
import {mediaPostUpdateAPI} from "../../../state/enities/lib/crudPosts/api/mediaPostUpdateAPI"
import {initDatabase} from "../../../state/enities/lib/crudPosts/db/initDatabase"
import {
    CREATE_AFTER,
    CREATE_BEFORE,
    CREATE_FIRST,
    CREATE_LAST,
    READ_ALL,
    UPDATE_ONE_JSON_FIELD,
    UPDATE_SHIFT_BOTTOM,
    UPDATE_SHIFT_TOP,
    UPDATE_SWAP_TWO_LINES,
} from "../../../state/enities/lib/crudPosts/lib/constants"
import {mediaPostActions} from "../../../state/enities/posts/mediaPostsSlice"
import {useSQLWeb} from "@/mi/providers/SQLiteWebProvider";
import {useSQLNative} from "@/mi/providers/SQLiteNativeProvider";
import {useSQLiteGlobal} from "@/app/_layout";

export function AppCRUDSQLiteDemol() {
    const supabaseUrl: any = process.env.EXPO_PUBLIC_SUPABASE_URL
    const supabaseKey: any = process.env.EXPO_PUBLIC_SUPABASE_KEY

    const [supabase, setSupabase] = useState(createClient(supabaseUrl, supabaseKey))

    const _adapter: any = useSQLiteGlobal()
    const db: any = _adapter.useSQLiteMi()

    const [lastPostGUID, setLastPostGUID] = useState("")
    const [mediaPostsArray, setMediaPostsArray] = useState<any>([])

    const [spbMediaPostArray, setSpbMediaPostArray] = useState([])

    const spbMediaPostReadAPI = async () => {
        // create table movies (
        //     id bigint generated by default as identity primary key,
        //     name test,
        //     description test
        // );

        // insert into movies
        // (id, name, description)
        // values
        // (
        //     111,
        //     'The Empire Strikes Back',
        //     'After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda.'
        // ),
        //     ( 222,
        //             'Return of the Jedi',
        //             'After a daring mission to rescue Han Solo from Jabba the Hutt, the Rebels dispatch to Endor to destroy the second Death Star.'
        //     );

        // select * from movies

        const {data, error: error1} = await supabase.from("movies").select(`id`)
        console.log("===== movies", data)
        console.log("===== error1", error1)

        const {data: postsArray, error: error2} = await supabase
            .from("posts-d0e57854-7b10-49a5-b6a8-78b3c8196db5")
            .select("mediaPostGUID")

        console.log("===== postsArray", postsArray)
        console.log("===== error2", error2)
        // Alert.alert(JSON.stringify(postsArray))
        const _postsArray: any = postsArray
        setSpbMediaPostArray(_postsArray)
    }

    const firstScreenLoad = async () => {
        const resultRead = await mediaPostReadAPI({
            dbHandle: db,
            tableName: "items1",
            readData: {
                readMode: READ_ALL,
                dbHandle: db,
                tableName: "items1",
            },
        })
        setMediaPostsArray(resultRead.result)

        console.log("███████████████ firstScreenLoad resultRead", resultRead)
    }

    useEffect(() => {
        spbMediaPostReadAPI()
        firstScreenLoad()
    }, [])

    const dispatch = useDispatch()

    // Alert.alert(JSON.stringify(mediaPostsArray));

    const sqLiteAdapter: any = _adapter

    return (
        <View style={styles.container}>
            <View
                style={[
                    // eslint-disable-next-line react-native/no-inline-styles
                    {justifyContent: "flex-start", flexDirection: "column", height: 1700},
                    styles.container,
                ]}
            >
                <Text style={styles.heading}>SQLite Example</Text>

                {/*/!*██████████████████ 1st code █████████*!/*/}
                {/*<View style={styles.flexRow}>*/}
                {/*    <TextInput*/}
                {/*        onChangeText={(test) => setText(test)}*/}
                {/*        onSubmitEditing={async () => {*/}
                {/*            await addItemAsync(db, test);*/}
                {/*            await refetchItems();*/}
                {/*            setText('');*/}
                {/*        }}*/}
                {/*        placeholder="what do you need to do?"*/}
                {/*        style={styles.input}*/}
                {/*        value={test}*/}
                {/*    />*/}
                {/*</View>*/}

                {/*<ScrollView style={styles.listArea}>*/}
                {/*    <View style={styles.sectionContainer}>*/}
                {/*        <Text style={styles.sectionHeading}>Todo</Text>*/}
                {/*        {todoItems.map((item) => (*/}
                {/*            <Item*/}
                {/*                key={item.id}*/}
                {/*                item={item}*/}
                {/*                onPressItem={async (id) => {*/}
                {/*                    await updateItemAsDoneAsync(db, id);*/}
                {/*                    await refetchItems();*/}
                {/*                }}*/}
                {/*            />*/}
                {/*        ))}*/}
                {/*    </View>*/}
                {/*    <View style={styles.sectionContainer}>*/}
                {/*        <Text style={styles.sectionHeading}>Completed</Text>*/}
                {/*        {doneItems.map((item) => (*/}
                {/*            <Item*/}
                {/*                key={item.id}*/}
                {/*                item={item}*/}
                {/*                onPressItem={async (id) => {*/}
                {/*                    await deleteItemAsync(db, id);*/}
                {/*                    await refetchItems();*/}
                {/*                }}*/}
                {/*            />*/}
                {/*        ))}*/}
                {/*    </View>*/}
                {/*</ScrollView>*/}
                {/*/!*██████████████████ 1st code █████████*!/*/}
                <Button
                    onPress={() => {
                        sqLiteAdapter.updateDbConfig({dbName: "db88"})
                    }}
                    title="Set Database 111"
                    color="#849999"
                    accessibilityLabel="Init Database tables"
                />

                <Button
                    onPress={() => {
                        sqLiteAdapter.updateDbConfig({dbName: "db555"})
                    }}
                    title="Set Database 222"
                    color="#849999"
                    accessibilityLabel="Init Database tables"
                />

                <Button
                    onPress={() => {
                        const doAsync = async () => {
                            try {
                                await initDatabase(db, {})
                            } catch (error) {
                                console.log("█████ 333 initDatabase Error ", error)
                            }
                        }
                        doAsync()
                    }}
                    title="Init Database"
                    color="#841584"
                    accessibilityLabel="Init Database tables"
                />

                <Button
                    title="CREATE LAST" //█████████████████ CREATE ███████████████████
                    color="blue"
                    accessibilityLabel="Init Database tables"
                    onPress={() => {
                        const doAsync = async () => {
                            const GUID = "Post-" + Date.now()
                            const createData: any = {
                                tableName: "items1",
                                createMode: CREATE_LAST,
                                mediaPostOwnerGUID: "111",
                                mediaPostGUID: "222-" + GUID,
                                mediaPostJSON: JSON.stringify({
                                    mediaPostTitle: "title " + GUID,
                                    mediaPostDescription: "description" + GUID,
                                }),
                            }

                            await mediaPostCreateAPI({
                                dbHandle: db,
                                createData,
                            })

                            await firstScreenLoad()
                        }

                        doAsync()
                    }}
                />

                <Button
                    title="CHANGE 1->2" //█████████████████ CHANGE ███████████████████
                    color="darkcyan"
                    accessibilityLabel="Init Database tables"
                    onPress={() => {
                        const doAsync = async () => {
                            const updateData = {
                                updateMode: UPDATE_SWAP_TWO_LINES,
                                tableName: "items1",
                                mediaPostGUID1: mediaPostsArray[0].mediaPostGUID,
                                mediaPostGUID2: mediaPostsArray[1].mediaPostGUID,
                                orderInList1: mediaPostsArray[0].orderInList,
                                orderInList2: mediaPostsArray[1].orderInList,
                                mediaPostOwnerGUID: mediaPostsArray[0].mediaPostOwnerGUID,
                            }
                            const resultUpdate = await mediaPostUpdateAPI({
                                dbHandle: db,
                                tableName: "items1",
                                updateData: updateData,
                            })

                            console.log("=== ████████ resultUpdate CHANGE 1->2 ", resultUpdate)

                            firstScreenLoad()
                        }
                        doAsync()
                    }}
                />

                <Button
                    title="CREATE" //█████████████████ CREATE ███████████████████
                    color="blue"
                    accessibilityLabel="Init Database tables"
                    onPress={() => {
                        const doAsync = async () => {
                            const GUID = "Post-" + Date.now()
                            const createData: any = {
                                tableName: "items1",
                                createMode: CREATE_FIRST,
                                mediaPostOwnerGUID: "111",
                                mediaPostGUID: "222-" + GUID,
                                mediaPostJSON: JSON.stringify({
                                    mediaPostTitle: "title " + GUID,
                                    mediaPostDescription: "description" + GUID,
                                }),
                            }

                            const resultCreate = await mediaPostCreateAPI({
                                dbHandle: db,
                                createData,
                                doAfter: (resultSelect2: any) => {
                                    console.log("█████ resultSelect2 ", resultSelect2)
                                    console.log("█████ resultSelect2 ", resultSelect2[resultSelect2.length - 1])
                                    setLastPostGUID(resultSelect2[resultSelect2.length - 1].mediaPostGUID)
                                    setMediaPostsArray(resultSelect2)
                                },
                                ifError: (errorData: any) => {
                                    console.log("█████ CREATE Error", errorData.toString())
                                    setLastPostGUID(errorData.toString())
                                },
                            })

                            const resultRead = await mediaPostReadAPI({
                                dbHandle: db,
                                tableName: "items1",
                                readData: {
                                    readMode: READ_ALL,
                                    dbHandle: db,
                                    tableName: "items1",
                                },
                            })
                            setMediaPostsArray(resultRead.result)

                            console.log("███████████████ resultCreate", resultCreate)
                            console.log("███████████████ resultRead", resultRead)
                        }
                        doAsync()
                    }}
                />
                {/* eslint-disable-next-line react-native/no-color-literals */}
                <Text style={{color: "red", height: 32}}>{lastPostGUID}</Text>

                <Button
                    title="DELETE LAST" //████████████████████████████████████
                    color="brown"
                    accessibilityLabel="Init Database tables"
                    onPress={() => {
                        const doAsync = async () => {
                            try {
                                const deleteData: any = {
                                    tableName: "items1",
                                    mediaPostGUID: lastPostGUID,
                                }

                                await mediaPostDeleteAPI({
                                    dbHandle: db,
                                    deleteData,
                                })

                                firstScreenLoad()
                            } catch (error) {
                                console.log("█████ DELETE Error while updating student", error)
                            }
                        }
                        doAsync()
                    }}
                />

                <View>
                    <Text>Items1</Text>
                    {!Array.isArray(mediaPostsArray) || mediaPostsArray.length === 0 ? (
                        <Text>No Posts...</Text>
                    ) : (
                        Array.isArray(mediaPostsArray) &&
                        mediaPostsArray.map((el: any, indexInList) => {
                            return (
                                // eslint-disable-next-line react-native/no-inline-styles
                                <View key={el.mediaPostGUID} style={{padding: 10, flexDirection: "row"}}>
                                    {/* eslint-disable-next-line react-native/no-inline-styles */}
                                    <View style={{flexDirection: "column"}}>
                                        {/* eslint-disable-next-line react-native/no-inline-styles */}
                                        <View style={{flexDirection: "row"}}>
                                            {/* eslint-disable-next-line react-native/no-inline-styles */}
                                            <Text style={{width: 150}}>{el.mediaPostJSON.mediaPostTitle}</Text>
                                            {/* eslint-disable-next-line react-native/no-inline-styles */}
                                            <Text style={{width: 50}}>{el.orderInList}</Text>
                                        </View>
                                        {/* eslint-disable-next-line react-native/no-inline-styles */}
                                        <Text style={{width: 150}}>{el.mediaPostJSON?.updateField}</Text>
                                    </View>
                                    <Button
                                        title="UPDATE" //████████████████████████████████████
                                        color="orange"
                                        accessibilityLabel="Init Database tables"
                                        onPress={() => {
                                            const doAsync = async () => {
                                                const updateData = {
                                                    updateMode: UPDATE_ONE_JSON_FIELD,
                                                    mediaPostGUID: el.mediaPostGUID,
                                                    updateFieldName: "updateField",
                                                    updateFieldValue: el.mediaPostJSON?.updateField + "█",
                                                    // mediaPostTitle:el.mediaPostJSON.mediaPostTitle + "█",
                                                }
                                                // const resultUpdate = await mediaPostUpdateAPI({
                                                //     dbHandle:db,
                                                //     tableName:"items1",
                                                //     updateData:updateData,
                                                // })
                                                // console.log("=== ████████ resultUpdate ",resultUpdate)

                                                console.log("███ update START")
                                                dispatch(
                                                    mediaPostActions.updateOne({
                                                        tableName: "items1",
                                                        updateData: updateData,
                                                    }),
                                                )

                                                firstScreenLoad()
                                            }
                                            doAsync()
                                        }}
                                    />

                                    <Button
                                        title="DEL" //█████████████████ DELETE ████████████████
                                        color="red"
                                        accessibilityLabel="Init Database tables"
                                        onPress={() => {
                                            const doAsync = async () => {
                                                const deleteData: any = {
                                                    tableName: "items1",
                                                    mediaPostGUID: el.mediaPostGUID,
                                                    reSelect: true,
                                                }

                                                const resultSelect2: any = await mediaPostDeleteAPI({
                                                    dbHandle: db,
                                                    tableName: "items1",
                                                    deleteData,
                                                })

                                                console.log("█████ DELETE resultSelect2", resultSelect2)

                                                firstScreenLoad()
                                            }
                                            doAsync()
                                        }}
                                    />

                                    <Button
                                        title="CREATE AFTER" //█████████████████ CREATE ███████████████████
                                        color="blue"
                                        accessibilityLabel="AFTER"
                                        onPress={() => {
                                            const doAsync1 = async () => {
                                                const GUID = "Post-" + Date.now()
                                                const createData: any = {
                                                    tableName: "items1",
                                                    createMode: CREATE_AFTER,
                                                    mediaPostOwnerGUID: "111",
                                                    mediaPostGUID: el.mediaPostGUID,
                                                    mediaPostGUIDNew: "new-post-" + GUID,
                                                    mediaPostJSON: JSON.stringify({
                                                        mediaPostTitle: "title " + GUID,
                                                        mediaPostDescription: "description" + GUID,
                                                    }),
                                                }

                                                // const resultCreate = await mediaPostCreateAPI({
                                                //     dbHandle:db,
                                                //     createData,
                                                //
                                                // })
                                                // console.log("resultCreate1",resultCreate)

                                                console.log("███ create START")
                                                dispatch(
                                                    mediaPostActions.createOne({
                                                        createData,
                                                    }),
                                                )

                                                await firstScreenLoad()
                                            }

                                            console.log("doAsync1")
                                            doAsync1()
                                        }}
                                    />
                                    <Button
                                        title="CREATE BEFORE" //█████████████████ CREATE ███████████████████
                                        color="green"
                                        accessibilityLabel="CREATE_BEFORE"
                                        onPress={() => {
                                            const doAsync1 = async () => {
                                                const GUID = "Post-" + Date.now()
                                                const createData: any = {
                                                    tableName: "items1",
                                                    createMode: CREATE_BEFORE,
                                                    mediaPostOwnerGUID: "111",
                                                    mediaPostGUID: el.mediaPostGUID,
                                                    mediaPostGUIDNew: "new-post-" + GUID,
                                                    mediaPostJSON: JSON.stringify({
                                                        mediaPostTitle: "title " + GUID,
                                                        mediaPostDescription: "description" + GUID,
                                                    }),
                                                }

                                                await mediaPostCreateAPI({
                                                    dbHandle: db,
                                                    createData,
                                                })

                                                // console.log("resultCreate1",resultCreate)

                                                await firstScreenLoad()
                                            }

                                            // console.log("doAsync1")
                                            doAsync1()
                                        }}
                                    />

                                    <Button
                                        title="SHIFT BOTTOM" //█████████████████ BOTTOM ███████████████████
                                        color="brown"
                                        onPress={() => {
                                            const doAsync = async () => {
                                                const updateData = {
                                                    tableName: "items1",
                                                    updateMode: UPDATE_SHIFT_BOTTOM,
                                                    mediaPostGUID: el.mediaPostGUID,
                                                    mediaPostOwnerGUID: el.mediaPostOwnerGUID,
                                                }
                                                const resultUpdate = await mediaPostUpdateAPI({
                                                    dbHandle: db,
                                                    updateData: updateData,
                                                })

                                                console.log("=== ████████ resultUpdate CHANGE 1->2 ", resultUpdate)

                                                firstScreenLoad()
                                            }
                                            doAsync()
                                        }}
                                    />

                                    <Button
                                        title="SHIFT TOP" //█████████████████ BOTTOM ███████████████████
                                        color="darkred"
                                        onPress={() => {
                                            const doAsync = async () => {
                                                const updateData = {
                                                    tableName: "items1",
                                                    updateMode: UPDATE_SHIFT_TOP,
                                                    mediaPostGUID: el.mediaPostGUID,
                                                    mediaPostOwnerGUID: el.mediaPostOwnerGUID,
                                                }
                                                const resultUpdate = await mediaPostUpdateAPI({
                                                    dbHandle: db,
                                                    updateData: updateData,
                                                })

                                                console.log("=== ████████ resultUpdate UPDATE_SHIFT_TOP ", resultUpdate)

                                                firstScreenLoad()
                                            }
                                            doAsync()
                                        }}
                                    />

                                    <Button
                                        title={"UP " + indexInList.toString()} //█████████████████ UP ███████████████████
                                        color="darkcyan"
                                        onPress={() => {
                                            const doAsync = async () => {
                                                const i1 = indexInList
                                                const i2 = indexInList - 1

                                                const updateData = {
                                                    updateMode: UPDATE_SWAP_TWO_LINES,
                                                    tableName: "items1",
                                                    mediaPostGUID1: mediaPostsArray[i2].mediaPostGUID,
                                                    mediaPostGUID2: mediaPostsArray[i1].mediaPostGUID,
                                                    orderInList1: mediaPostsArray[i2].orderInList,
                                                    orderInList2: mediaPostsArray[i1].orderInList,
                                                    mediaPostOwnerGUID: mediaPostsArray[i1].mediaPostOwnerGUID,
                                                }
                                                const resultUpdate = await mediaPostUpdateAPI({
                                                    dbHandle: db,
                                                    tableName: "items1",
                                                    updateData: updateData,
                                                })

                                                console.log("=== ████████ resultUpdate CHANGE 1->2 ", resultUpdate)

                                                firstScreenLoad()
                                            }

                                            const i1 = indexInList

                                            if (i1 <= 0) {
                                                console.log("This position is just 1st!")
                                                if (Platform.OS === "web") {
                                                    window.alert("Attetion please - This position is just 1st!")
                                                } else {
                                                    Alert.alert("Attetion please", "This position is just 1st!")
                                                }
                                                return
                                            }
                                            doAsync()
                                        }}
                                    />

                                    <Button
                                        title={"Down " + indexInList.toString()} //█████████████████ UP ███████████████████
                                        color="darkgreen"
                                        onPress={() => {
                                            const doAsync = async () => {
                                                const i1 = indexInList
                                                const i2 = indexInList + 1

                                                const updateData = {
                                                    updateMode: UPDATE_SWAP_TWO_LINES,
                                                    tableName: "items1",
                                                    mediaPostGUID1: mediaPostsArray[i2].mediaPostGUID,
                                                    mediaPostGUID2: mediaPostsArray[i1].mediaPostGUID,
                                                    orderInList1: mediaPostsArray[i2].orderInList,
                                                    orderInList2: mediaPostsArray[i1].orderInList,
                                                    mediaPostOwnerGUID: mediaPostsArray[i1].mediaPostOwnerGUID,
                                                }
                                                const resultUpdate = await mediaPostUpdateAPI({
                                                    dbHandle: db,
                                                    tableName: "items1",
                                                    updateData: updateData,
                                                })

                                                console.log("=== ████████ resultUpdate CHANGE 1->2 ", resultUpdate)

                                                firstScreenLoad()
                                            }

                                            const i1 = indexInList

                                            if (i1 === mediaPostsArray.length - 1) {
                                                console.log("This position is just Last!")
                                                if (Platform.OS === "web") {
                                                    window.alert("Attetion please - This position is just Last!")
                                                } else {
                                                    Alert.alert("Attetion please", "This position is just Last!")
                                                }
                                                return
                                            }
                                            doAsync()
                                        }}
                                    />
                                </View>
                            )
                        })
                    )}

                    <Text>{JSON.stringify(spbMediaPostArray)}</Text>
                </View>
            </View>
        </View>
    )
}

export const styles = StyleSheet.create({
    container: {
        backgroundColor: "lightblue",
        flex: 1,
        flexDirection: "column",
        paddingTop: 20,
    },
    flexRow: {
        flexDirection: "row",
    },
    heading: {
        fontSize: 20,
        fontWeight: "bold",
        textAlign: "center",
    },
    input: {
        borderColor: "#4630eb",
        borderRadius: 4,
        borderWidth: 1,
        flex: 1,
        height: 48,
        margin: 16,
        padding: 8,
    },
    item: {
        backgroundColor: "#fff",
        borderColor: "#000",
        borderWidth: 1,
        padding: 8,
    },
    itemDone: {
        backgroundColor: "#1c9963",
    },
    itemText: {
        color: "#000",
    },
    itemTextDone: {
        color: "#fff",
    },
    listArea: {
        backgroundColor: "#f0f0f0",
        flex: 1,
        paddingTop: 16,
    },
    sectionContainer: {
        marginBottom: 16,
        marginHorizontal: 16,
    },
    sectionHeading: {
        fontSize: 18,
        marginBottom: 8,
    },
})
